// <auto-generated />
namespace ProyectoXalli_Gentella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class estadoOrden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estadoOrden));
        
        string IMigrationMetadata.Id
        {
            get { return "202008021732381_estadoOrden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
