// <auto-generated />
namespace ProyectoXalli_Gentella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModificacionesModelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificacionesModelo));
        
        string IMigrationMetadata.Id
        {
            get { return "202004221508094_ModificacionesModelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
