// <auto-generated />
namespace ProyectoXalli_Gentella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class renombreIngrediente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renombreIngrediente));
        
        string IMigrationMetadata.Id
        {
            get { return "202007202159033_renombreIngrediente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
