// <auto-generated />
namespace ProyectoXalli_Gentella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modificandoModelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificandoModelo));
        
        string IMigrationMetadata.Id
        {
            get { return "202007181458572_modificandoModelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
